name: Sync with notion

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main
    paths:
      - 'README.md' # Specify the path to the README file

jobs:
  notion_sync:
    runs-on: ubuntu-latest
    name: Sync README to Notion
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Notion Sync Action
        uses: Novia-RDI-Seafaring/notion-sync-action@main
        with:
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_page_id: ${{ secrets.NOTION_PAGE_ID }}
          repo_description: MERI Parameter Extraction